config/routes.rb
FlashingDeal::Application.routes.draw do

	resources :authentications
	resources :blogs, :only => :index
	resources :categories, :only => :show
	resources :comments, :only => [:index, :create, :destroy]
  resources :deals do
  	collection { post :sort }
  	resources :shares
  	member do
  		get :frame
  		get :watchers
  		post :score_up
  		post :score_down
  		get :add_to_queue
  		get :make_queue
  		get :make_top_deal
  		get :make_flashback
  		get :make_remove
  		get :make_dead
  		get :show_overlay
  	end
  end
  resources :editmarks
  resources :feedbacks, :only => [:index, :create, :destroy]
  resources :forgot_names
  resources :friendships, :only => [:create, :update, :destroy]
  resources :locations, :only => :show
  resources :messages, :only => [:index, :show, :create, :update]
  resources :newsletters do
  	member do
  		get :email
  		get :subscribed
  		post :select
  	end
  end
  resources :notifications, :only => :index
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :posts do
  	member do
  		get :publish
  	end
  end
  resources :referrals, :only => :index
  resources :relationships, :only => [:index, :create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shares, :only => [:create, :destroy]
  resources :stars, :only => :create
  resources :subcomments, :only => [:create, :destroy]
  resources :users do
  	member do
  		get :name
  		get :email
  		get :password
  		get :photo
  		get :friends
  		get :message
  		get :watching
  	end
  end
# Authentications
	match '/auth/:provider/callback' => 'authentications#create'
	match '/auth/failure' => 'authentications#failure'
	match '/signup/twitter/email' => 'authentications#twitter_email', :as => :twitter_email
	match '/signup/twitter/email/new' => 'authentications#twitter_new', :as => :twitter_new
	match '/google/oauth' => 'authentications#google_oauth', :as => :google_oauth
	match '/google/access' => 'authentications#google_access', :as => :google_access
	match '/google/auth' => 'authentications#google_auth', :as => :google_auth
# Blogs
  match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain == 'blog' }
#	match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' && r.subdomain != 'flashingdeals' }
# Deals
  root :to => 'deals#featured_deals'
  match '/featured' => 'deals#featured_deals', :as => :featured_deals
	match '/flashingdeal/:id' => 'deals#frame', :as => :frame
	match '/community' => 'deals#community_deals', :as => :community_deals
	match '/flashmob-deals' => 'deals#flashmob_deals', :as => :flashmob_deals
	match '/clear-dead-deals' => 'deals#clear_dead_deals', :as => :clear_dead_deals
	match '/queue' => 'deals#queue', :as => :queue
	match '/rising-deals' => 'deals#rising_deals', :as => :rising_deals
	match '/search' => 'deals#search', :as => :search
  match '/create-deals' => 'deals#create_deals', :as => :create_deals
	match '/empty-queue' => 'deals#empty_queue', :as => :empty_queue
	match '/featured/all' => 'deals#featured_deals_all', :as => :featured_deals_all
# Friendships
	match '/friendships/accept/:name' => 'friendships#accept'
# Messages	
	match '/read-all' => 'messages#read_all', :as => :read_all
  match '/unread-all' => 'messages#unread_all', :as => :unread_all
# Newsletters
	match '/subscribed-users' => 'newsletters#subscribed_users', :as => :subscribed_users
	match '/unsubscribed-users' => 'newsletters#unsubscribed_users', :as => :unsubscribed_users
	match '/monthly-subscribed-users' => 'newsletters#monthly_subscribed_users', :as => :monthly_subscribed_users
	match '/unsubscribed-reply-alert-users' => 'newsletters#unsubscribed_reply_alert_users', :as => :unsubscribed_reply_alert_users
	match '/unsubscribed-friend-alert-users' => 'newsletters#unsubscribed_friend_alert_users', :as => :unsubscribed_friend_alert_users
	match '/email-subscribed-users' => 'newsletters#email_subscribed_users', :as => :email_subscribed_users
	match '/email-select-users' => 'newsletters#email_select_users', :as => :email_select_users
# Pages
  match '/about' => 'pages#about', :as => :about
  match '/team' => 'pages#team', :as => :team
  match '/partner' => 'pages#partner', :as => :partner
  match '/support' => 'pages#support', :as => :support
  match '/contact' => 'pages#contact', :as => :contact
  match '/terms' => 'pages#terms', :as => :terms
  match '/privacy' => 'pages#privacy', :as => :privacy
  
  match '/test' => 'pages#test', :as => :test
  match '/test2' => 'pages#test2', :as => :test2
  match '/test3' => 'pages#test3', :as => :test3
# Partners
	match '/satori' => 'partners#satori_deals', :as => :satori_deals
# Sessions  
  match '/login'  => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/hide-featured' => 'sessions#hide_featured', :as => :hide_featured
  match '/hide-community' => 'sessions#hide_community', :as => :hide_community
  match '/hide-category' => 'sessions#hide_category', :as => :hide_category
  
  match '/hide-signup-message' => 'sessions#hide_signup_message', :as => :hide_signup_message
  match '/hide-featured-deals-info' => 'sessions#hide_flashback_info', :as => :hide_flashback_info
  match '/hide-community-deals-info' => 'sessions#hide_flashmob_info', :as => :hide_flashmob_info
  match '/hide-categories-info' => 'sessions#hide_categories_info', :as => :hide_categories_info
# Shares  
  match '/remove-shared-deals' => 'shares#remove_shared_deals', :as => :remove_shared_deals
# Users
  match '/signup' => 'users#new'
  match '/feed' => 'users#my_feed', :as => :my_account
  match '/my-deals' => 'users#my_deals', :as => :my_deals
  match '/my-friends' => 'users#my_friends', :as => :my_friends
  match '/friend-requests' => 'users#friend_requests', :as => :friend_requests
  match '/shared' => 'users#shared', :as => :shared_deals
  match '/invite' => 'users#invite', :as => :invite
  match '/invite-gmail' => 'users#invite_gmail', :as => :invite_gmail
  match "/signup/:id" => 'users#signup', :as => :referral_signup_path
  match '/email-invites' => 'users#email_invite', :as => :email_invite
  match '/gmail-invites' => 'users#gmail_invite', :as => :gmail_invite
  match '/unsubscribe' => 'users#unsubscribe', :as => :unsubscribe
  match '/unsubscribe-me' => 'users#unsubscribe_me', :as => :unsubscribe_me
  match '/unsubscribe-reply-alerts' => 'users#unsubscribe_reply_alert', :as => :unsubscribe_reply_alert
  match '/unsubscribe-reply-alerts-me' => 'users#unsubscribe_reply_alert_me', :as => :unsubscribe_reply_alert_me
  match '/unsubscribe-friend-alerts' => 'users#unsubscribe_friend_alert', :as => :unsubscribe_friend_alert
  match '/unsubscribe-friend-alerts-me' => 'users#unsubscribe_friend_alert_me', :as => :unsubscribe_friend_alert_me
  match '/email-monthly' => 'users#email_monthly', :as => :email_monthly
  match '/game-room' => 'users#game_room', :as => :game_room
  match '/user-sent-invite' => 'users#user_sent_invite', :as => :user_sent_invite
  match '/account' => 'users#me_account', :as => :me_account
# Friends
	match '/user/list/friends/friends-list' => 'friends#friends_list', :as => :friends
# Ajax
	match '/ajax' => 'ajax#ajax'
	match '/ajax/ajax_received_messages' => 'ajax#ajax_received_messages'
	match '/ajax/ajax_friend_requests' => 'ajax#ajax_friend_requests'
	match '/ajax/ajax_shared_deals' => 'ajax#ajax_shared_deals'
	match '/ajax/ajax_notification' => 'ajax#ajax_notification'
	match '/ajax/ajax_notifications_update' => 'ajax#ajax_notifications_update'
# 404
  match '*url' => 'pages#page_not_found', :as => :page_not_found
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	attr_accessible :name, :info1, :info2, :info3, :info4, :info5, :info6, :deal1, :deal2, :deal3, :deal4, :deal5, :deal6, :deal7, :deal8, :emailed
	
	validates_presence_of :name, :unique => true
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
	before_filter :authenticate
	before_filter :admin_user
	
	def subscribed_users
		@title = "Subscribed Users"
		@users = User.where("subscribe = ?", true).order("name ASC")
	end
	
	def unsubscribed_users
		@title = "Unsubscribed Users"
		@users = User.where("subscribe = ?", false).order("name ASC")
		render :subscribed_users
	end
	
	def monthly_subscribed_users
		@title = "Monthly Subscribed Users"
		@users = User.where("monthly = ?", true).order("name ASC")
		render :subscribed_users
	end
	
	def unsubscribed_reply_alert_users
		@title = "Unsubscribed Reply Alert Users"
		@users = User.where("reply_alert = ?", false).order("name ASC")
		render :subscribed_users
	end
	
	def unsubscribed_friend_alert_users
		@title = "Unsubscribed Friend Alert Users"
		@users = User.where("friend_alert = ?", false).order("name ASC")
		render :subscribed_users
	end
	
	def email
		@newsletter = Newsletter.find(params[:id])
		@title = "Email #{@newsletter.name}"
		@users = User.where("subscribe = ? OR monthly = ?", true, true).order("name ASC")
	end
	
	def subscribed
		@newsletter = Newsletter.find(params[:id])
		@newsletter.update_attribute(:emailed, true)
    User.where("subscribe = ? OR monthly = ?", true, true).order("name ASC").each do |user|
      if Rails.env.production?
      	UserMailer.delay.newsletter(user, @newsletter)
      else
      	UserMailer.newsletter(user, @newsletter).deliver
      end
    end
		flash[:success] = "#{@newsletter.name} successfully emailed to all subscribed users."
		redirect_to newsletters_path
	end
	
	def select
		@newsletter = Newsletter.find(params[:id])
		@newsletter.update_attribute(:emailed, true)
		emails = params[:email_select_check].to_a.sort
    emails.each do |email|
      if Rails.env.production?
        UserMailer.delay.newsletter_select(email, @newsletter)
      else
        UserMailer.newsletter_select(email, @newsletter).deliver
      end
    end
		flash[:success] = "#{@newsletter.name} successfully emailed to select users."
		redirect_to newsletters_path
	end
	
  def index
  	@newsletters = Newsletter.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
  	@title = "Newsletters"
  end
  
  def show
  	@newsletter = Newsletter.find(params[:id])
  	deal_nil = []
  	deal1 = Deal.find_by_id(@newsletter.deal1)
  	deal2 = Deal.find_by_id(@newsletter.deal2)
  	deal3 = Deal.find_by_id(@newsletter.deal3)
  	deal4 = Deal.find_by_id(@newsletter.deal4)
  	deal5 = Deal.find_by_id(@newsletter.deal5)
  	deal6 = Deal.find_by_id(@newsletter.deal6)
  	deal7 = Deal.find_by_id(@newsletter.deal7)
  	deal8 = Deal.find_by_id(@newsletter.deal8)
  	if deal1.nil?
  		deal_nil.push(@newsletter.deal1)
  	end
  	if deal2.nil?
  		deal_nil.push(@newsletter.deal2)
  	end
  	if deal3.nil?
  		deal_nil.push(@newsletter.deal3)
  	end
  	if deal4.nil?
  		deal_nil.push(@newsletter.deal4)
  	end
  	if deal5.nil?
  		deal_nil.push(@newsletter.deal5)
  	end
  	if deal6.nil?
  		deal_nil.push(@newsletter.deal6)
  	end
  	if deal7.nil?
  		deal_nil.push(@newsletter.deal7)
  	end
  	if deal8.nil?
  		deal_nil.push(@newsletter.deal8)
  	end
  	if deal1.nil? && !@newsletter.deal1.nil? || deal2.nil? && !@newsletter.deal2.nil? || deal3.nil? && !@newsletter.deal3.nil? || deal4.nil? && !@newsletter.deal4.nil? || deal5.nil? && !@newsletter.deal5.nil? || deal6.nil? && !@newsletter.deal6.nil? || deal7.nil? && !@newsletter.deal7.nil? || deal8.nil? && !@newsletter.deal8.nil?
  		flash[:error] = "Deal #{deal_nil.join(' ')} cannot be found."
  		redirect_to edit_newsletter_path(@newsletter)
  	else
  		render :layout => false
  	end
  end

  def new
  	@title = "Create Newsletter"
  	@newsletter = Newsletter.new
  end
  
  def create
  	deal_nil = []
  	deal1 = Deal.find_by_id(params[:newsletter][:deal1])
  	deal2 = Deal.find_by_id(params[:newsletter][:deal2])
  	deal3 = Deal.find_by_id(params[:newsletter][:deal3])
  	deal4 = Deal.find_by_id(params[:newsletter][:deal4])
  	deal5 = Deal.find_by_id(params[:newsletter][:deal5])
  	deal6 = Deal.find_by_id(params[:newsletter][:deal6])
  	deal7 = Deal.find_by_id(params[:newsletter][:deal7])
  	deal8 = Deal.find_by_id(params[:newsletter][:deal8])
  	if deal1.nil?
  		deal_nil.push(params[:newsletter][:deal1])
  	end
  	if deal2.nil?
  		deal_nil.push(params[:newsletter][:deal2])
  	end
  	if deal3.nil?
  		deal_nil.push(params[:newsletter][:deal3])
  	end
  	if deal4.nil?
  		deal_nil.push(params[:newsletter][:deal4])
  	end
  	if deal5.nil?
  		deal_nil.push(params[:newsletter][:deal5])
  	end
  	if deal6.nil?
  		deal_nil.push(params[:newsletter][:deal6])
  	end
  	if deal7.nil?
  		deal_nil.push(params[:newsletter][:deal7])
  	end
  	if deal8.nil?
  		deal_nil.push(params[:newsletter][:deal8])
  	end
		@newsletter = Newsletter.new(params[:newsletter])
		if deal1.nil? && params[:newsletter][:deal1] != "" || deal2.nil? && params[:newsletter][:deal2] != "" || deal3.nil? && params[:newsletter][:deal3] != "" || deal4.nil? && params[:newsletter][:deal4] != "" || deal5.nil? && params[:newsletter][:deal5] != "" || deal6.nil? && params[:newsletter][:deal6] != "" || deal7.nil? && params[:newsletter][:deal7] != "" || deal8.nil? && params[:newsletter][:deal8] != ""
			flash[:error] = "Deal #{deal_nil.join(' ')} cannot be found."
  		render :new
  	else
			if @newsletter.save
	  		flash[:success] = "Newsletter successfully created."
	  		redirect_to newsletters_path
	  	else
	  		render :new
	  	end
	  end
  end

  def edit
  	@title = "Edit Newsletter"
  	@newsletter = Newsletter.find(params[:id])
  end

  def update
  	deal_nil = []
  	deal1 = Deal.find_by_id(params[:newsletter][:deal1])
  	deal2 = Deal.find_by_id(params[:newsletter][:deal2])
  	deal3 = Deal.find_by_id(params[:newsletter][:deal3])
  	deal4 = Deal.find_by_id(params[:newsletter][:deal4])
  	deal5 = Deal.find_by_id(params[:newsletter][:deal5])
  	deal6 = Deal.find_by_id(params[:newsletter][:deal6])
  	deal7 = Deal.find_by_id(params[:newsletter][:deal7])
  	deal8 = Deal.find_by_id(params[:newsletter][:deal8])
  	if deal1.nil?
  		deal_nil.push(params[:newsletter][:deal1])
  	end
  	if deal2.nil?
  		deal_nil.push(params[:newsletter][:deal2])
  	end
  	if deal3.nil?
  		deal_nil.push(params[:newsletter][:deal3])
  	end
  	if deal4.nil?
  		deal_nil.push(params[:newsletter][:deal4])
  	end
  	if deal5.nil?
  		deal_nil.push(params[:newsletter][:deal5])
  	end
  	if deal6.nil?
  		deal_nil.push(params[:newsletter][:deal6])
  	end
  	if deal7.nil?
  		deal_nil.push(params[:newsletter][:deal7])
  	end
  	if deal8.nil?
  		deal_nil.push(params[:newsletter][:deal8])
  	end
  	@newsletter = Newsletter.find(params[:id])
  	if deal1.nil? && params[:newsletter][:deal1] != "" || deal2.nil? && params[:newsletter][:deal2] != "" || deal3.nil? && params[:newsletter][:deal3] != "" || deal4.nil? && params[:newsletter][:deal4] != "" || deal5.nil? && params[:newsletter][:deal5] != "" || deal6.nil? && params[:newsletter][:deal6] != "" || deal7.nil? && params[:newsletter][:deal7] != "" || deal8.nil? && params[:newsletter][:deal8] != ""
			flash[:error] = "Deal #{deal_nil.join(' ')} cannot be found."
  		render :edit
  	else
	  	if @newsletter.update_attributes(params[:newsletter])
	  		flash[:success] = "Newsletter updated."
	  		redirect_to newsletters_path
	  	else
	  		render :edit
	  	end
	  end
  end

  def destroy
  	@newsletter = Newsletter.find(params[:id])
  	@newsletter.destroy
  	flash[:notice] = "Newsletter deleted."
  	redirect_to newsletters_path
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_newsletter.html.erb
<div class="newsletter">
	<%= link_to newsletter do %>
		<h1>
			<b><%= newsletter.name %></b> <span class="grey_150">(<%= newsletter.created_at.strftime("%b %d, %y") %>)</span>
			<% if newsletter.emailed? %>
				<span class="red">Emailed</span>
			<% end %>
		</h1>
	<% end %>
	<h2>
		# Of Deals:
		<% if newsletter.deal1.nil? %>
			0
		<% elsif !newsletter.deal8.nil? %>
			8
		<% elsif !newsletter.deal7.nil? %>
			7
		<% elsif !newsletter.deal6.nil? %>
			6
		<% elsif !newsletter.deal5.nil? %>
			5
		<% elsif !newsletter.deal4.nil? %>
			4
		<% elsif !newsletter.deal3.nil? %>
			3
		<% elsif !newsletter.deal2.nil? %>
			2
		<% elsif !newsletter.deal1.nil? %>
			1
		<% end %>
	</h2>
	<p><%= newsletter.info1 %></p>
	<p><%= newsletter.info2 %></p>
	<p><%= newsletter.info3 %></p>
	<p><%= newsletter.info4 %></p>
	<p><%= newsletter.info5 %></p>
	<p><%= newsletter.info6 %></p>
	<div id="newsletter_edit_delete">
		<ul>
			<li><%= link_to "Edit", edit_newsletter_path(newsletter) %></li>
			<li><%= link_to "Delete", newsletter, :method => :delete, :confirm => "Are you sure you want to delete this newsletter?" %></li>
			<li><%= link_to "Email", email_newsletter_path(newsletter) %></li>
		</ul>
	</div>
</div>

app/views/newsletters/_newsletter_side.html.erb
<div id="newsletter_side">
	<ul>
		<li><%= link_to "Newsletters", newsletters_path %></li>
		<li><%= link_to "Create Newsletter", new_newsletter_path %></li>
		<li><%= link_to "Subscribed Users", subscribed_users_path %></li>
		<li><%= link_to "Unsubscribed Users", unsubscribed_users_path %></li>
		<li><%= link_to "Monthly Subscribed Users", monthly_subscribed_users_path %></li>
		<li><%= link_to "Unsubscribed Reply Alert Users", unsubscribed_reply_alert_users_path %></li>
		<li><%= link_to "Unsubscribed Friend Alert Users", unsubscribed_friend_alert_users_path %></li>
	</ul>
</div>

app/views/newsletters/create.html.erb
<h1>Newsletters#create</h1>
<p>Find me in app/views/newsletters/create.html.erb</p>

app/views/newsletters/destroy.html.erb
<h1>Newsletters#destroy</h1>
<p>Find me in app/views/newsletters/destroy.html.erb</p>

app/views/newsletters/edit.html.erb
<%= render 'newsletter_side' %>
<div id="new_newsletter">
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>">
			<%= link_to image_tag("/assets/close.png"), "javascript: void(0);", :onclick => "closeFlashUp()", :class => "flash_close" %><%= value %>
		</div>
	<% end %>
	<%= form_for @newsletter do |f| %>
		<%= render 'users/error_messages', :object => f.object %>
		<div class="field">
			<p>Name: <%= f.text_field :name, :autocomplete => "off", :placeholder => "Required" %></p>
		</div>
		<div class="field">
			<p>Info 1: <%= f.text_area :info1, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 2: <%= f.text_area :info2, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 3: <%= f.text_area :info3, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 4: <%= f.text_area :info4, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 5: <%= f.text_area :info5, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 6: <%= f.text_area :info6, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Deal 1: <%= f.text_field :deal1, :autocomplete => "off", :placeholder => "2305 (The Deal's ID)" %></p>
		</div>
		<div class="field">
			<p>Deal 2: <%= f.text_field :deal2, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 3: <%= f.text_field :deal3, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 4: <%= f.text_field :deal4, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 5: <%= f.text_field :deal5, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 6: <%= f.text_field :deal6, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 7: <%= f.text_field :deal7, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 8: <%= f.text_field :deal8, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="action">
			<%= f.submit "Update" %>
		</div>
	<% end %>
</div>

app/views/newsletters/email.html.erb
<%= render 'newsletter_side' %>
<div id="email_newsletter">
	<div id="email_subscribed_users">
		<p id="newsletter_header"><%= @newsletter.name %></p>
		<%= link_to "Email Subscribed Users (#{@users.size})", subscribed_newsletter_path(@newsletter), :confirm => "Are you sure you want to email all subscribed users?" %>
	</div>
	<div id="email_select_users">
		<%= form_tag select_newsletter_path(@newsletter), :method => :post do %>
			<% @users.each do |user| %>
				<div id="newsletter_user_<%= user.id %>" class="newsletter_user">
					<input class="newsletter_user_check" type="checkbox" name="email_select_check[]" value="<%= user.email %>">
					<div id="newsletter_user_name">
						<p><b>Name:</b> <%= user.name %></p>
					</div>
					<div id="newsletter_user_email">
						<p><b>Email:</b> <%= user.email %></p>
					</div>
					<div class="clear"></div>
				</div>
			<% end %>
	</div>
	<div class="action">
		<%= submit_tag "Email Select Users", :name => nil %>
	</div>
	<% end %>
</div>

app/views/newsletters/index.html.erb
<%= render 'newsletter_side' %>
<div id="newsletter_list">
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>">
			<%= link_to image_tag("/assets/close.png"), "javascript: void(0);", :onclick => "closeFlashUp()", :class => "flash_close" %><%= value %>
		</div>
	<% end %>
	<h1 class="newsletters_header">Newsletters (<%= Newsletter.all.size %>)</h1>
	<%= render @newsletters %>
	<%= will_paginate @newsletters, :separator => "" %>
</div>

app/views/newsletters/new.html.erb
<%= render 'newsletter_side' %>
<div id="new_newsletter">
	<% flash.each do |key, value| %>
		<div class="flash <%= key %>">
			<%= link_to image_tag("/assets/close.png"), "javascript: void(0);", :onclick => "closeFlashUp()", :class => "flash_close" %><%= value %>
		</div>
	<% end %>
	<%= form_for @newsletter do |f| %>
		<%= render 'users/error_messages', :object => f.object %>
		<div class="field">
			<p>Name: <%= f.text_field :name, :autocomplete => "off", :placeholder => "Required" %></p>
		</div>
		<div class="field">
			<p>Info 1: <%= f.text_area :info1, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 2: <%= f.text_area :info2, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 3: <%= f.text_area :info3, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 4: <%= f.text_area :info4, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 5: <%= f.text_area :info5, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Info 6: <%= f.text_area :info6, :autocomplete => "off" %></p>
		</div>
		<div class="field">
			<p>Deal 1: <%= f.text_field :deal1, :autocomplete => "off", :placeholder => "2305 (The Deal's ID)" %></p>
		</div>
		<div class="field">
			<p>Deal 2: <%= f.text_field :deal2, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 3: <%= f.text_field :deal3, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 4: <%= f.text_field :deal4, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 5: <%= f.text_field :deal5, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 6: <%= f.text_field :deal6, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 7: <%= f.text_field :deal7, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="field">
			<p>Deal 8: <%= f.text_field :deal8, :autocomplete => "off", :placeholder => "Fill in the above deal before filling in this." %></p>
		</div>
		<div class="action">
			<%= f.submit "Create" %>
		</div>
	<% end %>
</div>

app/views/newsletters/subscribed_users.html.erb
<%= render 'newsletter_side' %>
<div id="subscribed_users_list">
	<p id="subscribed_users_size">Users: <%= @users.size %></p>
	<ul>
		<% @users.each do |user| %>
			<li><%= link_to user.name, user %></li>
		<% end %>
	</ul>
</div>

app/views/newsletters/update.html.erb
<h1>Newsletters#update</h1>
<p>Find me in app/views/newsletters/update.html.erb</p>