config/routes.rb
FlashingDeal::Application.routes.draw do

	resources :authentications
	resources :blogs, :only => :index
	resources :categories, :only => :show
	resources :comments, :only => [:index, :create, :destroy]
  resources :deals do
  	collection { post :sort }
  	resources :shares
  	member do
  		get :frame
  		get :watchers
  		post :score_up
  		post :score_down
  		get :add_to_queue
  		get :make_queue
  		get :make_top_deal
  		get :make_flashback
  		get :make_remove
  		get :make_dead
  		get :show_overlay
  	end
  end
  resources :editmarks
  resources :feedbacks, :only => [:index, :create, :destroy]
  resources :forgot_names
  resources :friendships, :only => [:create, :update, :destroy]
  resources :locations, :only => :show
  resources :messages, :only => [:index, :show, :create, :update]
  resources :newsletters do
  	member do
  		get :email
  		get :subscribed
  		post :select
  	end
  end
  resources :notifications, :only => :index
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :posts do
  	member do
  		get :publish
  	end
  end
  resources :referrals, :only => :index
  resources :relationships, :only => [:index, :create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shares, :only => [:create, :destroy]
  resources :stars, :only => :create
  resources :subcomments, :only => [:create, :destroy]
  resources :users do
  	member do
  		get :name
  		get :email
  		get :password
  		get :photo
  		get :friends
  		get :message
  		get :watching
  	end
  end
# Authentications
	match '/auth/:provider/callback' => 'authentications#create'
	match '/auth/failure' => 'authentications#failure'
	match '/signup/twitter/email' => 'authentications#twitter_email', :as => :twitter_email
	match '/signup/twitter/email/new' => 'authentications#twitter_new', :as => :twitter_new
	match '/google/oauth' => 'authentications#google_oauth', :as => :google_oauth
	match '/google/access' => 'authentications#google_access', :as => :google_access
	match '/google/auth' => 'authentications#google_auth', :as => :google_auth
# Blogs
  match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain == 'blog' }
#	match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' && r.subdomain != 'flashingdeals' }
# Deals
  root :to => 'deals#featured_deals'
  match '/featured' => 'deals#featured_deals', :as => :featured_deals
	match '/flashingdeal/:id' => 'deals#frame', :as => :frame
	match '/community' => 'deals#community_deals', :as => :community_deals
	match '/flashmob-deals' => 'deals#flashmob_deals', :as => :flashmob_deals
	match '/clear-dead-deals' => 'deals#clear_dead_deals', :as => :clear_dead_deals
	match '/queue' => 'deals#queue', :as => :queue
	match '/rising-deals' => 'deals#rising_deals', :as => :rising_deals
	match '/search' => 'deals#search', :as => :search
  match '/create-deals' => 'deals#create_deals', :as => :create_deals
	match '/empty-queue' => 'deals#empty_queue', :as => :empty_queue
	match '/featured/all' => 'deals#featured_deals_all', :as => :featured_deals_all
# Friendships
	match '/friendships/accept/:name' => 'friendships#accept'
# Messages	
	match '/read-all' => 'messages#read_all', :as => :read_all
  match '/unread-all' => 'messages#unread_all', :as => :unread_all
# Newsletters
	match '/subscribed-users' => 'newsletters#subscribed_users', :as => :subscribed_users
	match '/unsubscribed-users' => 'newsletters#unsubscribed_users', :as => :unsubscribed_users
	match '/monthly-subscribed-users' => 'newsletters#monthly_subscribed_users', :as => :monthly_subscribed_users
	match '/unsubscribed-reply-alert-users' => 'newsletters#unsubscribed_reply_alert_users', :as => :unsubscribed_reply_alert_users
	match '/unsubscribed-friend-alert-users' => 'newsletters#unsubscribed_friend_alert_users', :as => :unsubscribed_friend_alert_users
	match '/email-subscribed-users' => 'newsletters#email_subscribed_users', :as => :email_subscribed_users
	match '/email-select-users' => 'newsletters#email_select_users', :as => :email_select_users
# Pages
  match '/about' => 'pages#about', :as => :about
  match '/team' => 'pages#team', :as => :team
  match '/partner' => 'pages#partner', :as => :partner
  match '/support' => 'pages#support', :as => :support
  match '/contact' => 'pages#contact', :as => :contact
  match '/terms' => 'pages#terms', :as => :terms
  match '/privacy' => 'pages#privacy', :as => :privacy
  
  match '/test' => 'pages#test', :as => :test
  match '/test2' => 'pages#test2', :as => :test2
  match '/test3' => 'pages#test3', :as => :test3
# Partners
	match '/satori' => 'partners#satori_deals', :as => :satori_deals
# Sessions  
  match '/login'  => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/hide-featured' => 'sessions#hide_featured', :as => :hide_featured
  match '/hide-community' => 'sessions#hide_community', :as => :hide_community
  match '/hide-category' => 'sessions#hide_category', :as => :hide_category
  
  match '/hide-signup-message' => 'sessions#hide_signup_message', :as => :hide_signup_message
  match '/hide-featured-deals-info' => 'sessions#hide_flashback_info', :as => :hide_flashback_info
  match '/hide-community-deals-info' => 'sessions#hide_flashmob_info', :as => :hide_flashmob_info
  match '/hide-categories-info' => 'sessions#hide_categories_info', :as => :hide_categories_info
# Shares  
  match '/remove-shared-deals' => 'shares#remove_shared_deals', :as => :remove_shared_deals
# Users
  match '/signup' => 'users#new'
  match '/feed' => 'users#my_feed', :as => :my_account
  match '/my-deals' => 'users#my_deals', :as => :my_deals
  match '/my-friends' => 'users#my_friends', :as => :my_friends
  match '/friend-requests' => 'users#friend_requests', :as => :friend_requests
  match '/shared' => 'users#shared', :as => :shared_deals
  match '/invite' => 'users#invite', :as => :invite
  match '/invite-gmail' => 'users#invite_gmail', :as => :invite_gmail
  match "/signup/:id" => 'users#signup', :as => :referral_signup_path
  match '/email-invites' => 'users#email_invite', :as => :email_invite
  match '/gmail-invites' => 'users#gmail_invite', :as => :gmail_invite
  match '/unsubscribe' => 'users#unsubscribe', :as => :unsubscribe
  match '/unsubscribe-me' => 'users#unsubscribe_me', :as => :unsubscribe_me
  match '/unsubscribe-reply-alerts' => 'users#unsubscribe_reply_alert', :as => :unsubscribe_reply_alert
  match '/unsubscribe-reply-alerts-me' => 'users#unsubscribe_reply_alert_me', :as => :unsubscribe_reply_alert_me
  match '/unsubscribe-friend-alerts' => 'users#unsubscribe_friend_alert', :as => :unsubscribe_friend_alert
  match '/unsubscribe-friend-alerts-me' => 'users#unsubscribe_friend_alert_me', :as => :unsubscribe_friend_alert_me
  match '/email-monthly' => 'users#email_monthly', :as => :email_monthly
  match '/game-room' => 'users#game_room', :as => :game_room
  match '/user-sent-invite' => 'users#user_sent_invite', :as => :user_sent_invite
  match '/account' => 'users#me_account', :as => :me_account
# Friends
	match '/user/list/friends/friends-list' => 'friends#friends_list', :as => :friends
# Ajax
	match '/ajax' => 'ajax#ajax'
	match '/ajax/ajax_received_messages' => 'ajax#ajax_received_messages'
	match '/ajax/ajax_friend_requests' => 'ajax#ajax_friend_requests'
	match '/ajax/ajax_shared_deals' => 'ajax#ajax_shared_deals'
	match '/ajax/ajax_notification' => 'ajax#ajax_notification'
	match '/ajax/ajax_notifications_update' => 'ajax#ajax_notifications_update'
# 404
  match '*url' => 'pages#page_not_found', :as => :page_not_found
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
	belongs_to :deal
	
	validates_uniqueness_of :user_id, :scope => [:notice_id, :deal_id, :comment_id, :subcomment_id]
	
	default_scope :order => 'notifications.created_at DESC'
	
	def month_day
		self.created_at.strftime("%B %e")
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_filter :authenticate
	
	def index
		@title = "Notifications"
		@notifications = current_user.notifications.where("read = ? OR created_at > ?", false, (Time.now - (86400 * 14))).take(50)
		@notifications_days = @notifications.take(100).group_by(&:month_day)
		current_user.notifications.where("read = ?", false).each do |n|
			n.update_attribute(:read, true)
		end
		respond_to do |format|
			format.mobile { render :layout => 'application_in' }
		end
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
	<div id="notification">
		<%= link_to(Deal.find(notification.deal_id), :id => "notification_link") do %>
		<% end %>
		<h2><%= notification.created_at.strftime("%B %e") %></h2>
		<div id="notification_time">
			<%= notification.created_at.strftime("%l:%M %p") %>
		</div>
		<p><%= User.find(notification.user_id).name %> commented on <%= link_to Deal.find(notification.deal_id).name, Deal.find(notification.deal_id) %></p>
		<div class="clear"></div>
	</div>
</li>

app/views/notifications/_notification.mobile.erb
<div id="notification">
	<%= link_to(Deal.find(notification.deal_id), :class => "notificationDealLink") do %>
		<div id="notificationUserPhoto">
			<%= image_tag "/assets/lazyMobile.jpg", "data-original" => Deal.find(notification.deal_id).image, :class => "lazyLoad" %>
		</div>
		<p id="notificationInfo"><span class="anchorBlue"><%= User.find(notification.user_id).name %></span> commented on <%= Deal.find(notification.deal_id).name %></p>
		<p id="notificationTimeStamp">
			<% if (Time.now - notification.created_at)/86400 > 1 %>
				<%= notification.created_at.strftime("%B %d, %Y") %>
			<% else %>
				<%= time_ago_in_words(notification.created_at) %> ago
			<% end %>
		</p>
		<div class="clear"></div>
	<% end %>
</div>

app/views/notifications/index.html.erb
<div id="notifications">
	<p class="notifications_header">Notifications</p>
	<% @notifications_days.each do |month_day, notifications| %>
		<h2><%= month_day %></h2>
		<% for notification in notifications %>
			<div id="notification">
				<%= link_to(Deal.find(notification.deal_id), :id => "notification_link") do %>
				<% end %>
				<div id="notification_time">
					<%= notification.created_at.strftime("%l:%M %p") %>
				</div>
				<p><%= link_to User.find(notification.user_id).name, User.find(notification.user_id) %> commented on <%= link_to Deal.find(notification.deal_id).name, Deal.find(notification.deal_id) %></p>
				<div class="clear"></div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/notifications/index.mobile.erb
<div id="header" data-role="header">
	<%= link_to(me_account_path, :id => "backButton", "data-transition" => "slide", "data-direction" => "reverse", "data-role" => "none") do %>
		Back
	<% end %>
	<div class="headerPageTitle">
		Notifications
	</div>
	<%= link_to(root_path, :id => "blueBoltHome", "data-role" => "none") do %>
		<div></div>
	<% end %>
</div>
<div id="contentNoPad" data-role="content">
	<div id="notifications">
		<% if @notifications.empty? %>
			<p class="notificationsNone">You currently have none.</p>
		<% else %>
			<%= render @notifications %>
		<% end %>
	</div>
</div>