config/routes.rb
FlashingDeal::Application.routes.draw do

	resources :authentications
	resources :blogs, :only => :index
	resources :categories, :only => :show
	resources :comments, :only => [:index, :create, :destroy]
  resources :deals do
  	collection { post :sort }
  	resources :shares
  	member do
  		get :frame
  		get :watchers
  		post :score_up
  		post :score_down
  		get :add_to_queue
  		get :make_queue
  		get :make_top_deal
  		get :make_flashback
  		get :make_remove
  		get :make_dead
  		get :show_overlay
  	end
  end
  resources :editmarks
  resources :feedbacks, :only => [:index, :create, :destroy]
  resources :forgot_names
  resources :friendships, :only => [:create, :update, :destroy]
  resources :locations, :only => :show
  resources :messages, :only => [:index, :show, :create, :update]
  resources :newsletters do
  	member do
  		get :email
  		get :subscribed
  		post :select
  	end
  end
  resources :notifications, :only => :index
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :posts do
  	member do
  		get :publish
  	end
  end
  resources :referrals, :only => :index
  resources :relationships, :only => [:index, :create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shares, :only => [:create, :destroy]
  resources :stars, :only => :create
  resources :subcomments, :only => [:create, :destroy]
  resources :users do
  	member do
  		get :name
  		get :email
  		get :password
  		get :photo
  		get :friends
  		get :message
  		get :watching
  	end
  end
# Authentications
	match '/auth/:provider/callback' => 'authentications#create'
	match '/auth/failure' => 'authentications#failure'
	match '/signup/twitter/email' => 'authentications#twitter_email', :as => :twitter_email
	match '/signup/twitter/email/new' => 'authentications#twitter_new', :as => :twitter_new
	match '/google/oauth' => 'authentications#google_oauth', :as => :google_oauth
	match '/google/access' => 'authentications#google_access', :as => :google_access
	match '/google/auth' => 'authentications#google_auth', :as => :google_auth
# Blogs
  match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain == 'blog' }
#	match '', to: 'blogs#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' && r.subdomain != 'flashingdeals' }
# Deals
  root :to => 'deals#featured_deals'
  match '/featured' => 'deals#featured_deals', :as => :featured_deals
	match '/flashingdeal/:id' => 'deals#frame', :as => :frame
	match '/community' => 'deals#community_deals', :as => :community_deals
	match '/flashmob-deals' => 'deals#flashmob_deals', :as => :flashmob_deals
	match '/clear-dead-deals' => 'deals#clear_dead_deals', :as => :clear_dead_deals
	match '/queue' => 'deals#queue', :as => :queue
	match '/rising-deals' => 'deals#rising_deals', :as => :rising_deals
	match '/search' => 'deals#search', :as => :search
  match '/create-deals' => 'deals#create_deals', :as => :create_deals
	match '/empty-queue' => 'deals#empty_queue', :as => :empty_queue
	match '/featured/all' => 'deals#featured_deals_all', :as => :featured_deals_all
# Friendships
	match '/friendships/accept/:name' => 'friendships#accept'
# Messages	
	match '/read-all' => 'messages#read_all', :as => :read_all
  match '/unread-all' => 'messages#unread_all', :as => :unread_all
# Newsletters
	match '/subscribed-users' => 'newsletters#subscribed_users', :as => :subscribed_users
	match '/unsubscribed-users' => 'newsletters#unsubscribed_users', :as => :unsubscribed_users
	match '/monthly-subscribed-users' => 'newsletters#monthly_subscribed_users', :as => :monthly_subscribed_users
	match '/unsubscribed-reply-alert-users' => 'newsletters#unsubscribed_reply_alert_users', :as => :unsubscribed_reply_alert_users
	match '/unsubscribed-friend-alert-users' => 'newsletters#unsubscribed_friend_alert_users', :as => :unsubscribed_friend_alert_users
	match '/email-subscribed-users' => 'newsletters#email_subscribed_users', :as => :email_subscribed_users
	match '/email-select-users' => 'newsletters#email_select_users', :as => :email_select_users
# Pages
  match '/about' => 'pages#about', :as => :about
  match '/team' => 'pages#team', :as => :team
  match '/partner' => 'pages#partner', :as => :partner
  match '/support' => 'pages#support', :as => :support
  match '/contact' => 'pages#contact', :as => :contact
  match '/terms' => 'pages#terms', :as => :terms
  match '/privacy' => 'pages#privacy', :as => :privacy
  
  match '/test' => 'pages#test', :as => :test
  match '/test2' => 'pages#test2', :as => :test2
  match '/test3' => 'pages#test3', :as => :test3
# Partners
	match '/satori' => 'partners#satori_deals', :as => :satori_deals
# Sessions  
  match '/login'  => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/hide-featured' => 'sessions#hide_featured', :as => :hide_featured
  match '/hide-community' => 'sessions#hide_community', :as => :hide_community
  match '/hide-category' => 'sessions#hide_category', :as => :hide_category
  
  match '/hide-signup-message' => 'sessions#hide_signup_message', :as => :hide_signup_message
  match '/hide-featured-deals-info' => 'sessions#hide_flashback_info', :as => :hide_flashback_info
  match '/hide-community-deals-info' => 'sessions#hide_flashmob_info', :as => :hide_flashmob_info
  match '/hide-categories-info' => 'sessions#hide_categories_info', :as => :hide_categories_info
# Shares  
  match '/remove-shared-deals' => 'shares#remove_shared_deals', :as => :remove_shared_deals
# Users
  match '/signup' => 'users#new'
  match '/feed' => 'users#my_feed', :as => :my_account
  match '/my-deals' => 'users#my_deals', :as => :my_deals
  match '/my-friends' => 'users#my_friends', :as => :my_friends
  match '/friend-requests' => 'users#friend_requests', :as => :friend_requests
  match '/shared' => 'users#shared', :as => :shared_deals
  match '/invite' => 'users#invite', :as => :invite
  match '/invite-gmail' => 'users#invite_gmail', :as => :invite_gmail
  match "/signup/:id" => 'users#signup', :as => :referral_signup_path
  match '/email-invites' => 'users#email_invite', :as => :email_invite
  match '/gmail-invites' => 'users#gmail_invite', :as => :gmail_invite
  match '/unsubscribe' => 'users#unsubscribe', :as => :unsubscribe
  match '/unsubscribe-me' => 'users#unsubscribe_me', :as => :unsubscribe_me
  match '/unsubscribe-reply-alerts' => 'users#unsubscribe_reply_alert', :as => :unsubscribe_reply_alert
  match '/unsubscribe-reply-alerts-me' => 'users#unsubscribe_reply_alert_me', :as => :unsubscribe_reply_alert_me
  match '/unsubscribe-friend-alerts' => 'users#unsubscribe_friend_alert', :as => :unsubscribe_friend_alert
  match '/unsubscribe-friend-alerts-me' => 'users#unsubscribe_friend_alert_me', :as => :unsubscribe_friend_alert_me
  match '/email-monthly' => 'users#email_monthly', :as => :email_monthly
  match '/game-room' => 'users#game_room', :as => :game_room
  match '/user-sent-invite' => 'users#user_sent_invite', :as => :user_sent_invite
  match '/account' => 'users#me_account', :as => :me_account
# Friends
	match '/user/list/friends/friends-list' => 'friends#friends_list', :as => :friends
# Ajax
	match '/ajax' => 'ajax#ajax'
	match '/ajax/ajax_received_messages' => 'ajax#ajax_received_messages'
	match '/ajax/ajax_friend_requests' => 'ajax#ajax_friend_requests'
	match '/ajax/ajax_shared_deals' => 'ajax#ajax_shared_deals'
	match '/ajax/ajax_notification' => 'ajax#ajax_notification'
	match '/ajax/ajax_notifications_update' => 'ajax#ajax_notifications_update'
# 404
  match '*url' => 'pages#page_not_found', :as => :page_not_found
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged
	
	acts_as_voteable
	attr_accessible :name,
									:price,
									:value,
									:discount,
									:savings,
									:link,
									:image,
									:site,
									:rating,
									:up_rating,
									:down_rating,
									:metric,
									:tag,
									:posted,
									:city,
									:info,
									:top_deal,
									:flash_back,
									:deal_order,
									:queue,
									:time_in,
									:time_out,
									:view_count,
									:click_count,
									:comment_count,
									:point_count,
									:exclusive,
									:coupon,
									:rebate,
									:dead,
									:flashmob,
									:expires,
									:partner,
									:last_said
	
									
	validates :name, :presence => true 
							
	has_many :relationships, :foreign_key => "watched_id", :dependent => :destroy
	has_many :watchers, :through => :relationships, :source => :watcher
	
	has_many :connections, :dependent => :destroy
	has_many :categories, :through => :connections
	
	has_many :comments, :dependent => :destroy
	has_many :subcomments, :dependent => :destroy
	
	has_one :bond, :dependent => :destroy
	has_one :location, :through => :bond
	
	has_many :shares, :dependent => :destroy
	has_many :users, :through => :shares
	has_many :friends, :through => :shares, :source => :user
	
	has_many :editmarks, :dependent => :destroy
	
	has_many :notifications, :dependent => :destroy
	
	has_many :stars, :dependent => :destroy
	
	def self.search(search)
		if search
			if Rails.env.production?
				where("name ILIKE ? OR site ILIKE ?", "%#{search}%", "%#{search}%")
			else
				where("name LIKE ? OR site LIKE ?", "%#{search}%", "%#{search}%")
			end
		else
			scoped
		end
	end
	
	def self.search_flashmob(search)
		if search
			if Rails.env.production?
				where("metric = ? AND name ILIKE ? OR site ILIKE ?", -1, "%#{search}%", "%#{search}%")
			else
				where("metric = ? AND name LIKE ? OR site LIKE ?", -1, "%#{search}%", "%#{search}%")
			end
		else
			scoped
		end
	end
	
	def star_count
		if self.stars.size == 0
			"0"
		else
			array = []
			self.stars.each do |star|
				array.push(star.value)
			end
			array_total = array.inject { |sum, x| sum + x }
			array_avg = array_total.to_f/array.size.to_f
			"#{array_avg.round(1)}"
		end
	end
	
	def all_comments
		(self.comments.order("updated_at DESC").limit(5) + self.subcomments.order("created_at DESC").limit(5)).sort_by { |comment| comment.updated_at }.reverse.take(5)
	end
	
	def total_comments
		self.comments.size + self.subcomments.size	
	end
	
	def self.from_friends_of(user)
		unless (user.friends + user.inverse_friends).empty?
			friend_ids = (user.friends + user.inverse_friends).map(&:id).join(', ')
			deal_ids = Relationship.where("watcher_id IN (#{friend_ids})").map(&:watched_id).uniq.join(', ')
			where("id IN (#{deal_ids}) AND dead = ?", false).where("comment_count >= 3 OR comment_count >= 2 AND view_count >=  10 OR comment_count >= 1 AND view_count >= 20").order("last_said DESC")
		end
	end
end

app/helpers/deals_helper.rb
module DealsHelper
	
	def make_rising_deals
		make_slickdeals_deals
  	make_woot_deals
		make_fatwallet_deals
  	make_dealsplus_deals
  	make_dealnews_deals
  	make_dealigg_deals
  	make_todaysdod_deals
	end
	
	def make_flashmob_deals
		make_logicbuy_deals
  	make_techdealdigger_deals
		make_dealsplus_coupons
		make_brandname_coupons
		make_csb_deals
		make_techbargains_deals
		make_bradsdeals_deals
		make_onedaybuys_deals
		make_dealery_deals
	end
	
	# functions for @home_deals_four 
	
	def timeCheckMin1
		t = Time.now
		now = t.min
		if now >= 0 && now < 7
			@home_deals_four = @deals[0..3]
		elsif now >= 7 && now < 14
			@home_deals_four = @deals[1..4]
		elsif now >= 14 && now < 21
			@home_deals_four = @deals[2..5]
		elsif now >= 21 && now < 28
			@home_deals_four = @deals[3..6]
		elsif now >= 28 && now < 35
			@home_deals_four = @deals[4..7]
		elsif now >= 35 && now < 42
			@home_deals_four = @deals[5..8]
		elsif now >= 42 && now < 49
			@home_deals_four = @deals[6..8].push(@deals[0])
		elsif now >= 49 && now < 56
			@home_deals_four = @deals[7..8].push(@deals[0]).push(@deals[1])
		elsif now >= 56 && now < 60
			@home_deals_four = @deals[8..8].push(@deals[0]).push(@deals[1]).push(@deals[2])
		end
	end
	
	def timeCheckMinFourDeals
		t = Time.now
		now = t.min
		if now >= 0 && now < 3
			@home_deals_four = @deals[0..3]
		elsif now >= 3 && now < 6
			@home_deals_four = @deals[1..4]
		elsif now >= 6 && now < 9
			@home_deals_four = @deals[2..5]
		elsif now >= 9 && now < 12
			@home_deals_four = @deals[3..6]
		elsif now >= 12 && now < 15
			@home_deals_four = @deals[4..7]
		elsif now >= 15 && now < 18
			@home_deals_four = @deals[5..8]
		elsif now >= 18 && now < 21
			@home_deals_four = @deals[6..9]
		elsif now >= 21 && now < 24
			@home_deals_four = @deals[7..10]
		elsif now >= 24 && now < 27
			@home_deals_four = @deals[8..11]
		elsif now >= 27 && now < 30
			@home_deals_four = @deals[9..12]
		elsif now >= 30 && now < 33
			@home_deals_four = @deals[10..13]
		elsif now >= 33 && now < 36
			@home_deals_four = @deals[11..14]
		elsif now >= 36 && now < 39
			@home_deals_four = @deals[12..15]
		elsif now >= 39 && now < 42
			@home_deals_four = @deals[13..16]
		elsif now >= 42 && now < 45
			@home_deals_four = @deals[14..17]
		elsif now >= 45 && now < 48
			@home_deals_four = @deals[15..18]
		elsif now >= 48 && now < 51
			@home_deals_four = @deals[16..19]
		elsif now >= 51 && now < 54
			@home_deals_four = @deals[17..19].push(@deals[0])
		elsif now >= 54 && now < 57
			@home_deals_four = @deals[18..19].push(@deals[0]).push(@deals[1])
		elsif now >= 57 && now < 60
			@home_deals_four = @deals[19..19].push(@deals[0]).push(@deals[2]).push(@deals[3])
		end
	end
	
	def timeCheckMinNineDeals
		t = Time.now
		now = t.min
		if now >= 0 && now < 3
			@home_deals = @deals[0..8]
		elsif now >= 3 && now < 6
			@home_deals = @deals[1..9]
		elsif now >= 6 && now < 9
			@home_deals = @deals[2..10]
		elsif now >= 9 && now < 12
			@home_deals = @deals[3..11]
		elsif now >= 12 && now < 15
			@home_deals = @deals[4..12]
		elsif now >= 15 && now < 18
			@home_deals = @deals[5..13]
		elsif now >= 18 && now < 21
			@home_deals = @deals[6..14]
		elsif now >= 21 && now < 24
			@home_deals = @deals[7..15]
		elsif now >= 24 && now < 27
			@home_deals = @deals[8..16]
		elsif now >= 27 && now < 30
			@home_deals = @deals[9..17]
		elsif now >= 30 && now < 33
			@home_deals = @deals[10..18]
		elsif now >= 33 && now < 36
			@home_deals = @deals[11..19]
		elsif now >= 36 && now < 39
			@home_deals = @deals[12..19].push(@deals[0])
		elsif now >= 39 && now < 42
			@home_deals = @deals[13..19].push(@deals[0]).push(@deals[1])
		elsif now >= 42 && now < 45
			@home_deals = @deals[14..19].push(@deals[0]).push(@deals[1]).push(@deals[2])
		elsif now >= 45 && now < 48
			@home_deals = @deals[15..19].push(@deals[0]).push(@deals[1]).push(@deals[2]).push(@deals[3])
		elsif now >= 48 && now < 51
			@home_deals = @deals[16..19].push(@deals[0]).push(@deals[1]).push(@deals[2]).push(@deals[3]).push(@deals[4])
		elsif now >= 51 && now < 54
			@home_deals = @deals[17..19].push(@deals[0]).push(@deals[1]).push(@deals[2]).push(@deals[3]).push(@deals[4]).push(@deals[5])
		elsif now >= 54 && now < 57
			@home_deals = @deals[18..19].push(@deals[0]).push(@deals[1]).push(@deals[2]).push(@deals[3]).push(@deals[4]).push(@deals[5]).push(@deals[6])
		elsif now >= 57 && now < 60
			@home_deals = @deals[19..19].push(@deals[0]).push(@deals[1]).push(@deals[2]).push(@deals[3]).push(@deals[4]).push(@deals[5]).push(@deals[6]).push(@deals[7])
		end
	end
	
	# checks every hour, use this to move top_deals into flash_back
	def timeCheckHour
		t = Time.now
		now = t.hour
		if now >= 6 && now < 7
			@home_deals_four = @deals[0..3]
		elsif now >= 7 && now < 8
			@home_deals_four = @deals[1..4]
		elsif now >= 8 && now < 9
			@home_deals_four = @deals[2..5]
		elsif now >= 9 && now < 10
			@home_deals_four = @deals[3..6]
		elsif now >= 10 && now < 11
			@home_deals_four = @deals[4..7]
		elsif now >= 11 && now < 12
			@home_deals_four = @deals[5..8]
		elsif now >= 12 && now < 13
			@home_deals_four = @deals[6..8].push(@deals[0])
		elsif now >= 13 && now < 14
			@home_deals_four = @deals[7..8].push(@deals[0]).push(@deals[1])
		elsif now >= 14 && now < 15
			@home_deals_four = @deals[8..8].push(@deals[0]).push(@deals[1]).push(@deals[2])
		elsif now >= 15 && now < 16
			@home_deals_four = @deals[0..3]
		elsif now >= 16 && now < 17
			@home_deals_four = @deals[1..4]
		elsif now >= 17 && now < 18
			@home_deals_four = @deals[2..5]
		elsif now >= 18 && now < 19
			@home_deals_four = @deals[3..6]
		elsif now >= 19 && now < 20
			@home_deals_four = @deals[4..7]
		elsif now >= 20 && now < 21
			@home_deals_four = @deals[5..8]
		elsif now >= 21 && now < 22
			@home_deals_four = @deals[6..8].push(@deals[0])
		elsif now >= 22 && now < 23
			@home_deals_four = @deals[7..8].push(@deals[0]).push(@deals[1])
		elsif now >= 23 && now < 24
			@home_deals_four = @deals[8..8].push(@deals[0]).push(@deals[1]).push(@deals[2])
		elsif now >= 0 && now < 1
			@home_deals_four = @deals[0..3]
		elsif now >= 1 && now < 2
			@home_deals_four = @deals[1..4]
		elsif now >= 2 && now < 3
			@home_deals_four = @deals[2..5]
		elsif now >= 3 && now < 4
			@home_deals_four = @deals[3..6]
		elsif now >= 4 && now < 5
			@home_deals_four = @deals[4..7]
		elsif now >= 5 && now < 6
			@home_deals_four = @deals[5..8]
		end
	end
end

app/views/deals/_deal_info2.html.erb
<div id="deal_info2">
	<h2>Community Knowledge
		<% if signed_in? %>
			<% if current_user.admin? %>
				<span id="edit_the_flash"><%= link_to "Edit", "javascript:void(0);", :onclick => "toggleInfoEditForm();" %></span>
				<div id="comment_and_point_count">
					Comment Count: <span id="comment_count"><%= @deal.comment_count %></span> <span class="grey_75">|</span>
					Point Count: <span id="point_count"><%= @deal.point_count %></span>
				</div>
				<div id="view_and_click_count">Views: <%= @deal.view_count %> <span class="grey_75">|</span> Clicks: 
				<% if @deal.click_count.nil? %>
					0
				<% else %>
					<%= @deal.click_count %>
				<% end %>
				</div>
			<% end %>
		<% end %>
	</h2>
	<div id="deal_summary_container">
		<div id="info">
			<% if signed_in? %>
				<%= render 'the_flash_deal_info' %>
			<% else %>
				<p><%= to_html(auto_link(@deal.info, :all, :target => "_blank")) %></p>
			<% end %>
		</div>
		<% if signed_in? %>
			<% if current_user.admin? %>
				<div id="info_edit_the_flash">
					<%= render 'deal_info_form' %>
				</div>
			<% end %>
		<% end %>
		<div id="deal_side_panel">
			<div id="deal_summary_side_panel">
				<div id="watch_deal_info">
					Save this to your "My Deals" and never lose sight of it!
					<div id="watch_deal_info_triangle"></div>
				</div>
				<div class="add_deal">
					<% if signed_in? %>
						<%= render 'watch_form' %>
					<% else %>
						<div id="watch_form">
							<div class="actions">
								<%= link_to("javascript:void(0);", :class => "alertdim") do %>
									<input name="commit" type="submit" value="Watch" onmouseover="showWatchDealInfo()" onmouseout="hideWatchDealInfo()" onmouseclick="hideWatchDealInfo()">
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
				<div id="share_all_info">
					Share this deal with all your FD friends
					<div id="share_all_info_triangle"></div>
				</div>
				<% if signed_in? %>
					<div id="share_form">
						<%= render 'shares/share_all_form' %>
					</div>
				<% else %>
					<div id="share_form_signup">
						<%= link_to "Share", "javascript:void(0);", :onmouseover => "showShareAllInfo()", :onmouseout => "hideShareAllInfo()", :class => "alertdim" %>
					</div>
				<% end %>
			</div>
			<div id="deal_summary">
				<div id="user_like">
					<%= render "user_like" %>
				</div>
				<div id="user_dislike">
					<%= render "user_dislike" %>
				</div>
				<div id="flash_points">
					<div id="up">
						<% if signed_in? %>
							<%= link_to(score_up_deal_path(@deal), :onmouseover => "toggleUserLike()", :onmouseout => "toggleUserLike()", :method => :post, :remote => true, :id => "like") do %>
								<div id="like_arrow"></div>
							<% end %>
						<% else %>
							<%= link_to("javascript:void(0);", :id => "like", :onmouseover => "toggleUserLike()", :onmouseout => "toggleUserLike()", :class => "alertdim") do %>
								<div id="like_arrow"></div>
							<% end %>
						<% end %>
					</div>
					<div id="total_score">
						<h1><%= @deal.plusminus %></h1>
					</div>
					<div id="down">
						<% if signed_in? %>
							<%= link_to(score_down_deal_path(@deal), :onmouseover => "toggleUserDislike()", :onmouseout => "toggleUserDislike()", :method => :post, :remote => true, :id => "dislike") do %>
								<div id="dislike_arrow"></div>
							<% end %>
						<% else %>
							<%= link_to("javascript:void(0);", :id => "dislike", :onmouseover => "toggleUserDislike()", :onmouseout => "toggleUserDislike()", :class => "alertdim") do %>
								<div id="dislike_arrow"></div>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<% unless @deal.coupon.nil? && @deal.rebate.nil? %>
				<% unless @deal.coupon.blank? && @deal.rebate.blank? %>
					<div id="coupon_rebate">
						<% unless @deal.coupon.nil? || @deal.coupon.blank? %>
							<div id="deal_show_coupon">
								<h1>Coupon Code</h1>
								<p><%= @deal.coupon %></p>
							</div>
						<% end %>
						<% unless @deal.rebate.nil? || @deal.rebate.blank? %>
							<div id="deal_show_rebate">
								<h1>Rebate Link</h1>
								<p><%= link_to "#{@deal.rebate}", @deal.rebate, :target => "_blank" %></p>
							</div>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="clear"></div>
	<div id="the_flash">
		<% flash.each do |key, value| %>
  		<div class="flash <%= key %>">
  			<%= link_to image_tag("/assets/close.png"), "javascript: void(0);", :onclick => "closeFlashUp()", :class => "flash_close" %><%= value %>
			</div>
  	<% end %>
  	<div id="flash"></div>
  	<% if signed_in? %>
			<%= render 'comments/comment_form' %>
		<% end %>
		<div id="deal_show_comments_list">
			<%= render @comments %>
		</div>
	</div>
	<% if signed_in? %>
		<% if current_user.admin? %>
		<div id="delete_deal">
			<ul>
				<li><p><%= link_to "Add to Queue", add_to_queue_deal_path(@deal), :remote => true %></p></li>
				<li><p><%= link_to "Edit Deal", edit_deal_path(@deal) %></p></li>
				<% if current_user.gm? %>
					<li><p><%= link_to "Delete Deal", @deal, :method => :delete, :confirm => "Are you sure you want to delete this deal?", :title => "Delete #{@deal.name}" %></p></li>
				<% end %>
			</ul>
		</div>
		<% end %>
	<% end %>
</div>

app/views/deals/_endless_pagination.html.erb
<div id="endless_pagination">
	<%= will_paginate @deals, :separator => "" %>
</div>

app/views/deals/_unwatch.html.erb
<%= form_for current_user.relationships.find_by_watched_id(@deal), :html => { :method => :delete }, :remote => true do |f| %>
	<div class="actions">
		<%= f.submit "UnWatch" %>
	</div>
<% end %>

app/views/deals/_user_like.html.erb
<% if signed_in? %>
	<% if current_user.voted_for?(@deal) %>
		You like this deal
	<% else %>
		Like this deal
	<% end %>
<% else %>
	Like this deal
<% end %>
<div id="user_voted_triangle"></div>

app/views/deals/create_deals.html.erb
<% flash.each do |key, value| %>
	<div class="flash <%= key %>"><%= value %><%= link_to image_tag("/assets/close.png"), "javascript: void(0);", :onclick => "closeFlashUp()", :class => "flash_close" %></div>
<% end %>
<div id="create_deals">
	<div id="Create Rising Deals">
		<%= link_to "Create Rising Deals", create_rising_deals_path %>
	</div>
	<div id="Create FlashMob Deals">
		<%= link_to "Create FlashMob Deals", create_flashmob_deals_path %>
	</div>
</div>

app/views/deals/featured_deals_all.html.erb
<div id="deals_list">
	<div id="search">
		<% unless @deals.empty? %>
			<div class="paginate_range">
				<%= paginate_range(@deals, @deals_total_count) %>
			</div>
		<% end %>
		<div id="search_form">
		<%= form_tag featured_deals_all_path, :method => :get do %>
			<%= hidden_field_tag :sort, params[:sort] %>
			<%= hidden_field_tag :direction, params[:direction] %>
			<%= hidden_field_tag :deals_per_page, params[:deals_per_page] %>
			<%= text_field_tag :search, params[:search], :autocomplete => "off" %>
			<%= submit_tag "Search", :name => nil, :id => "search_button" %>
		<% end %>
		</div>
	</div>
	<% if @deals.empty? %>
		<div class="empty_category">
			<p>Woopsie! No matching deals...for now :)</p>
			<p><%= link_to "View other deals", featured_deals_path %></p>
		</div>
	<% end %>
	<a name="top"></a>
	<div id="rising_deals_list">
		<%= render :partial => "rising_deal", :collection => @deals, :as => :deal %>
	</div>
	<%= will_paginate @deals, :separator => "" %>
	<% unless @deals.count < 3 %>
		<div id="back_to_top">
			<strong>^</strong><%= link_to "Back to the Top", "javascript:void(0);", :class => "scroll_top" %>
		</div>
	<% end %>
</div>